import Image from './Image';

export default function () {
  return (
    <main className="grid grid-cols-6 gap-2 xs:gap-y-5 text-sm">
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-4 row-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />

      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />

      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-4 row-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image src={`/albums/wedding/0.jpg`} alt="wedding" />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image src={`/albums/wedding/0.jpg`} alt="wedding" />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image src={`/albums/wedding/0.jpg`} alt="wedding" />
      <Image src={`/albums/wedding/0.jpg`} alt="wedding" />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-4"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-4"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-3"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-2"
      />
      <Image
        src={`/albums/wedding/0.jpg`}
        alt="wedding"
        className="col-span-6"
      />
    </main>
  );
}

{
  /* <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' />
      <Image src={`/albums/wedding/0.jpg`} alt='wedding' className='col-span-2 h-[368px]' /> */
}
